### ISSUE TITLE
iOS/Android: Documentation: Should be "user::demo" instead of "user:demo"

### ISSUE THREAD

**Issue by hideki** [couchbaselabs/mobile-travel-sample#10]
http://docs-build.sc.couchbase.com:9000/develop/java#/2/2/0

> In the search box, enter "user:demo".

This should be "user::demo"

**Comment by jamesnocentini** [comment]
fixed in https://github.com/couchbaselabs/mobile-travel-sample/commit/6aea01cf78054b0ea6f362bfe3590d6bb4663c26
