### ISSUE TITLE
Unable to find package Couchbase.Lite.Support.Android. No packages exist with this id in source(s): nuget.org

### ISSUE THREAD

**Issue by amagne** [couchbaselabs/mobile-travel-sample#30]
I get this error when restoring Nugets packages in VS for mac : "Could not restore Nuget packages" when looking at the log it seems to be unable to find Couchbase.Lite.Support.Android nuget package.

**Comment by rajagp** [comment]
Please check latest instructions :  http://docs.couchbase.com/tutorials/travel-sample/develop/csharp/#/0/0/1

Fixed in https://github.com/couchbaselabs/mobile-travel-sample/commit/d905a713be674877a96504818fcc09f8bb6ef112
